name: Jokes

on:
  schedule:
    - cron: '0 0/15 8-17 * *'

jobs:
  generate-jokes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run Script
        run: |
          python main.py
